### ISSUE TITLE
proposal: Consider moving Vecty under its own GitHub organization

### ISSUE THREAD

**Issue by slimsag** [hexops/vecty#230]
Currently, Vecty lives under the GopherJS organization. This made sense for multiple reasons at the time, which I will go into further here. However, I believe it may be time for Vecty to move under its own organization and live at https://github.com/vecty/vecty

# Vecty: A brief history

Vecty originally started out as me looking into how a React-like framework could be done in Go, with an interesting twist: I didn't know React (and I still consider myself to not know React). This, I think, gave me an interesting perspective on how to achieve the _same goals as React_ without making it _feel_ like React stuffed into Go, but rather a Go developer's take on how component-based webapps could be written.

This idea got shared with @dmitshur, who then shared it with @neelance (author of GopherJS) and as it turned out he was also experimenting with the idea of React-in-GopherJS. After meeting up in person in SF, we came to chat about this significantly and he proved to me various flaws and incorrect assumptions that my (documentation-heavy) implementation at the time would have in comparison to his (undocumented) [implementation](https://github.com/gopherjs/vecty/tree/old). So after some discussion it made sense: Add documentation and use his implementation, and use the Vecty project name.

Much experimentation and many significant changes later, and Vecty is ironically not like either of the starting implementations. We're [still missing documentation](https://github.com/gopherjs/vecty/issues/31) and the actual implementation uses many different core concepts (mainly to remove boilerplate code that was hand-written or auto-generated in @neelance's initial implementation).

In Go 1.11, @neelance [added WebAssembly support to Go](https://github.com/golang/go/issues/18892) and support for it in Vecty has always been planned.

Today, the Go WebAssembly community is flourishing more and more, with even alternative Go implementations like @aykevl's [tinygo](https://github.com/aykevl/tinygo) popping up (which aims to produce ultra small binaries, making it an even more viable target for producing web applications).

It makes sense today that Vecty will support three primary compiler targets:

- GopherJS (as it always has)
- Go's native WebAssembly support
- TinyGo

All of these implementations have various tradeoffs between binary sizes, browser compatibility, standard library support, etc. and Vecty can and should support all of them soon.

## Should we move to a separate organization?

I think yes, with the main reasons being:

1. Vecty living under the GopherJS organization implicitly communicates that it is for GopherJS
    - GopherJS is likely to go into a sunsetting state soon, with more and more developers switching over to Go's native WebAssembly support. This may make it look like the "old" technology to newcomers (even if it isn't). Go 2 will be coming eventually and I anticipate there will not be enough developer time spent on GopherJS in the long run to support Go 2 (I would be happy to be wrong about this, however).
2. Vecty already requires a location to host other related repositories: https://github.com/vecty and putting those in the GopherJS namespace would obviously not make sense (we would pollute it).
3. My hope is that Vecty can one day be the defacto method of doing web UX's in Go in the long term, and that the Vecty github organization could act as a location for maintaining a set of curated Vecty packages similar to how golang.org/x/ contains curated Go packages.

## Notes

- None of this indicates my belief around GopherJS being an awesome project has changed. On the contrary, I think GopherJS was just the start of something big. :)

**Comment by pdf** [comment]
Makes sense I think.

**Comment by mfridman** [comment]
An interesting consideration here is whether vecty would make use of and/or support a wrapper such as gopherwasm.

A while ago @dmitshur  published the [Future of GopherJS and Go in the browser](https://medium.com/gopherjs/future-of-gopherjs-and-go-in-the-browser-cc1667468160). In an ideal world packages such as vecty could support multiple compiler targets with a well supported wrapper.

However, if development of such a wrapper were to stop, slowdown or not be able to keep up with the rapid pace of WASM development, what would that mean for the vecty project?

WASM is not yet subject to the Go 1 compatibility promise. So there will likely be breaking changes as development in this space moves forward.

There may be challenges if vecty moves to an organization and attempts to support multiple compiler targets.

For these reasons there can be an argument for keeping vecty coupled to the native implementation (GopherJS) and considering other solutions. This obviously isn't ideal, at all, because being able to make use of both for the near-future is still ideal.

E.g., being able to serve both WASM and JS, to support various browser versions, with JS as a fallback. 

If vecty could move to an organization and support multiple compiler targets that would be ideal.

**Comment by pdf** [comment]
> There may be challenges if vecty moves to an organization and attempts to support multiple compiler targets.

I don't believe the two are in any way coupled.

**Comment by slimsag** [comment]
> An interesting consideration here is whether vecty would make use of and/or support a wrapper such as gopherwasm.
>
> A while ago @dmitshur published the Future of GopherJS and Go in the browser. [...]

Thanks for linking me to that, I hadn't seen that blog post of his yet.

I like to think that Vecty can work well with gopherwasm if you want it to, but that we do not enforce that on you. If you want to stay in pure `gopherjs/js`, or pure `syscall/js`, that's up to you as a consumer of the library.  In specific, see my [comment here](https://github.com/gopherjs/vecty/pull/215#issuecomment-429591378) for how I plan to approach this.

**Comment by slimsag** [comment]
No, supporting 3 different backend is about 0.5% of the work needed to get a v1 release, and currently not having support for those 3 backends is causing others to consider writing their own web frameworks separately when they could theoretically be contributing to Vecty. For an idea of what we need for v1, see https://github.com/gopherjs/vecty/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0

Me and @pdf are currently the only major contributors to this project, and both of us lack a lot of time to contribute (I for example can only donate a few hours every few months, with all other time going towards work or family). At current pace, a v1 release is a long way out unless we get more major contributors or I start working on Vecty full time which is super unrealistic 😛

**Comment by Gee5ive** [comment]
Hey @slimsag that makes perfect sense, I haven't seen any other go client-side frameworks that look worth anything aside from https://github.com/myitcv/x/tree/master/react not sure how many people actually use it though. I'd love to help out in any way that I can with the project, I can maybe only spare a couple of hours a month myself, but I guess every little bit counts. Have to really dig into the code at some point just to get an idea of where to start though.

Hopefully, more people in the community will contribute to the project. Would be cool to write only Go code on the client and the server at some point.

**Comment by slimsag** [comment]
A great place to start is writing more test cases :)

**Comment by lunny** [comment]
Just do it and fork `github.com/vecty/vecty` to `github.com/gopherjs/vecty` for compitable.

**Comment by xoviat** [comment]
@slimsag I'd like for you to move the project to github.com/vecty/vecty. Then I'd like to move github.com/vecty-material/material to github.com/vecty/material. That repository would include the 'official' material design components for vecty.

I don't see a reason to put this off any longer; the URLs will break at some time and waiting is going to make things worse in the future.

**Comment by mpfaff** [comment]
I'd like to add that if you were to transfer the repository, GitHub *should* handle redirects to the new url.

**Comment by slimsag** [comment]
Hey folks - it's been a while since I originally proposed this and I wanted to provide an update and explain the next steps here.

Over the past year I've had increasingly less time to work on Vecty due to a number of other things pulling my attention away from it (family, work at Sourcegraph, and other life events.) This has meant Vecty has been, and continues to be, in a bit of maintenance mode.

I think it could become immensely valuable to the Go community and could become the best way to write web UIs in Go - but it'll require a bit of work to get there and, currently, I am the only one devoting time to it.

Outside of Vecty, I have a number of other ambitious projects going on and I would eventually like to have these lead to an organization which is able to fund the development of Vecty (among other open-source projects) - that is still several years away and I hope to do more work on Vecty before then.

In the meantime, I am corralling all of the projects I maintain into a single organization - https://github.com/hexops - and intend to move Vecty there. This should be a space where it can thrive all the same (and hopefully, in the distant future, much more than) as if it was in https://github.com/vecty

What this means is that:

- Vecty will move to https://github.com/hexops/vecty
- https://github.com/vecty/$repo repositories will move to https://github.com/hexops/vecty-$repo
- A majority of Vecty will remain in a monorepo, https://github.com/hexops/vecty - the only things that may be excluded from that monorepo will be lower-quality/stability experimental packages (material design components, etc.)
- We fulfill the original intent of this proposal ("Vecty living under the GopherJS organization implicitly communicates that it is for GopherJS")

**Comment by slimsag** [comment]
The above has been done in #268 - please [refer to the CHANGELOG](https://github.com/hexops/vecty/blob/master/doc/CHANGELOG.md) to update your import paths.

**Comment by VinceJnz** [comment]
What is going to happen with the documentation and material. Will they be moved into the new structure?
https://pkg.go.dev/github.com/gopherjs/vecty
https://github.com/vecty-material/material
