### ISSUE TITLE
Add Vocexplorer to projects-using-vecty.md

### ISSUE THREAD

**Issue by NateWilliams2** [hexops/vecty#272]
I've been working on this vecty application for a couple months and would love to have it featured on the projects-using-vecty document :-}

[Vocdoni Block Explorer](https://gitlab.com/vocdoni/vocexplorer) | A custom blockchain explorer for decentralized digital governance toolkit [Vocdoni.io](https://vocdoni.io/)

**Comment by slimsag** [comment]
Looks like a quite nice and complex UI, I'm sure many would be excited to see this!

I've gone ahead and added it exactly as you described above :)
